#if !defined(AFX__TRAYICON1_H__D2A9D0D8_7431_486F_8EA7_AB5953D5E99C__INCLUDED_)
#define AFX__TRAYICON1_H__D2A9D0D8_7431_486F_8EA7_AB5953D5E99C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_TrayIcon1 wrapper class

class C_TrayIcon1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_TrayIcon1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x30e583a6, 0x8e26, 0x11da, { 0xa1, 0xc2, 0x80, 0x7a, 0x50, 0xc1, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL Show(long Icon, LPCTSTR ToolTip);
	BOOL Animate(LPDISPATCH imgList, long Interval);
	BOOL StopAnimateing(long NewIcon);
	void ShowBalloon(LPCTSTR Prompt, LPCTSTR Title, long IconType, long Timeout);
	BOOL CreateToolTip(long lParentHwnd, long* X, long* y);
	void CloseBalloon();
	BOOL Hide();
	void ChangeIcon(long NewIcon);
	BOOL GetIsDisplayed();
	CString GetIconToolTip();
	void SetIconToolTip(LPCTSTR lpszNewValue);
	BOOL GetAnimateState();
	BOOL GetTrackPopMenu();
	void SetTrackPopMenu(BOOL bNewValue);
	void PopUp(long hmenu, long ParentWindow);
	long CreateToolTip2(long lParentHwnd);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__TRAYICON1_H__D2A9D0D8_7431_486F_8EA7_AB5953D5E99C__INCLUDED_)
