'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Cacadore.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Action is not attached with this task..
        '''</summary>
        Friend ReadOnly Property AcitIsNotAttached() As String
            Get
                Return ResourceManager.GetString("AcitIsNotAttached", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task&apos;s actions are not set to be presisted, please set ActionsPersistenceOperation property first..
        '''</summary>
        Friend ReadOnly Property ActNotPresisted() As String
            Get
                Return ResourceManager.GetString("ActNotPresisted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot invoke command.
        '''</summary>
        Friend ReadOnly Property CmdNotPresisted() As String
            Get
                Return ResourceManager.GetString("CmdNotPresisted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CrudObject property is not set to an ICrud object..
        '''</summary>
        Friend ReadOnly Property CrudObjNotSet() As String
            Get
                Return ResourceManager.GetString("CrudObjNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global members are not set to be presisted..
        '''</summary>
        Friend ReadOnly Property GlobNotPresisted() As String
            Get
                Return ResourceManager.GetString("GlobNotPresisted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group not set to be presisted, please set GroupPersistenceOperationValue property first..
        '''</summary>
        Friend ReadOnly Property GrpNotPresisted() As String
            Get
                Return ResourceManager.GetString("GrpNotPresisted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GroupsCollection are not set to be presisted, please set GroupsCollectionPersistenceOperation property first..
        '''</summary>
        Friend ReadOnly Property GrpsNotPresisted() As String
            Get
                Return ResourceManager.GetString("GrpsNotPresisted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to History are not set to be presisted, please set HistoryPersistenceOperation property first..
        '''</summary>
        Friend ReadOnly Property HistNotPresisted() As String
            Get
                Return ResourceManager.GetString("HistNotPresisted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid name, only alphanumeric characters are allowed..
        '''</summary>
        Friend ReadOnly Property InVaNa() As String
            Get
                Return ResourceManager.GetString("InVaNa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid task or taskId.
        '''</summary>
        Friend ReadOnly Property InvTskOrId() As String
            Get
                Return ResourceManager.GetString("InvTskOrId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Object reference not set to an instance of an object.
        '''</summary>
        Friend ReadOnly Property NoObjectFound() As String
            Get
                Return ResourceManager.GetString("NoObjectFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings are not set to be presisted, please set SettingsPersistenceOperation property first..
        '''</summary>
        Friend ReadOnly Property SetNotPresisted() As String
            Get
                Return ResourceManager.GetString("SetNotPresisted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task&apos;s triggers are not set to be presisted, please set TriggerPersistenceOperation property first..
        '''</summary>
        Friend ReadOnly Property TrgNotPresisted() As String
            Get
                Return ResourceManager.GetString("TrgNotPresisted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task not set to be presisted, please set TaskPersistenceOperation property first..
        '''</summary>
        Friend ReadOnly Property TskNotPresisted() As String
            Get
                Return ResourceManager.GetString("TskNotPresisted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task&apos;s variables are not set to be presisted, please set VariablesPersistenceOperation property first..
        '''</summary>
        Friend ReadOnly Property VarsNotPresisted() As String
            Get
                Return ResourceManager.GetString("VarsNotPresisted", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
