#if !defined(AFX__BALLOON1_H__C4224875_380D_408A_893E_9AB285EED2CF__INCLUDED_)
#define AFX__BALLOON1_H__C4224875_380D_408A_893E_9AB285EED2CF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_Balloon1 wrapper class

class C_Balloon1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_Balloon1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x30e583af, 0x8e26, 0x11da, { 0xa1, 0xc2, 0x80, 0x7a, 0x50, 0xc1, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void ShowBalloon(long* PHwnd, LPCTSTR Prompt, LPCTSTR Title, long IconType, long DelayTime, long Timeout);
	void Destroy();
	void SetForeColor(long nNewValue);
	long GetForeColor();
	void SetBackColor(long nNewValue);
	long GetBackColor();
	void SetStyle(long nNewValue);
	long GetStyle();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__BALLOON1_H__C4224875_380D_408A_893E_9AB285EED2CF__INCLUDED_)
