// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_balloon1.h"

/////////////////////////////////////////////////////////////////////////////
// C_Balloon1

IMPLEMENT_DYNCREATE(C_Balloon1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// C_Balloon1 properties

/////////////////////////////////////////////////////////////////////////////
// C_Balloon1 operations

void C_Balloon1::ShowBalloon(long* PHwnd, LPCTSTR Prompt, LPCTSTR Title, long IconType, long DelayTime, long Timeout)
{
	static BYTE parms[] =
		VTS_PI4 VTS_BSTR VTS_BSTR VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x6003000c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PHwnd, Prompt, Title, IconType, DelayTime, Timeout);
}

void C_Balloon1::Destroy()
{
	InvokeHelper(0x6003000e, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void C_Balloon1::SetForeColor(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030002, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Balloon1::GetForeColor()
{
	long result;
	InvokeHelper(0x68030002, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Balloon1::SetBackColor(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030001, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Balloon1::GetBackColor()
{
	long result;
	InvokeHelper(0x68030001, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Balloon1::SetStyle(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Balloon1::GetStyle()
{
	long result;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}
