'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TecDAL.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Action already attached to this task..
        '''</summary>
        Friend ReadOnly Property ActIsAlrdyAttached() As String
            Get
                Return ResourceManager.GetString("ActIsAlrdyAttached", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This action is not already attached to task..
        '''</summary>
        Friend ReadOnly Property ActIsNotSet() As String
            Get
                Return ResourceManager.GetString("ActIsNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No action found with the specified action id..
        '''</summary>
        Friend ReadOnly Property ActNotFound() As String
            Get
                Return ResourceManager.GetString("ActNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error adding task state..
        '''</summary>
        Friend ReadOnly Property AdingTskStErr() As String
            Get
                Return ResourceManager.GetString("AdingTskStErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The database appears to be damaged. Please re-install Cacadu..
        '''</summary>
        Friend ReadOnly Property dd() As String
            Get
                Return ResourceManager.GetString("dd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error updateing settings..
        '''</summary>
        Friend ReadOnly Property ErrUpSettings() As String
            Get
                Return ResourceManager.GetString("ErrUpSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global member is already defined..
        '''</summary>
        Friend ReadOnly Property GlobAlrdyDefined() As String
            Get
                Return ResourceManager.GetString("GlobAlrdyDefined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global member is not defined..
        '''</summary>
        Friend ReadOnly Property GlobNotDefined() As String
            Get
                Return ResourceManager.GetString("GlobNotDefined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A group with same id is already defined..
        '''</summary>
        Friend ReadOnly Property GrpIsAlrdyDefined() As String
            Get
                Return ResourceManager.GetString("GrpIsAlrdyDefined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group is not defined..
        '''</summary>
        Friend ReadOnly Property GrpIsNotDefined() As String
            Get
                Return ResourceManager.GetString("GrpIsNotDefined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No group found for the specified group id..
        '''</summary>
        Friend ReadOnly Property GrpNotFound() As String
            Get
                Return ResourceManager.GetString("GrpNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred to Database, 
        '''Cacadu will restore the Database to a previous state..
        '''</summary>
        Friend ReadOnly Property mald() As String
            Get
                Return ResourceManager.GetString("mald", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No task with such id..
        '''</summary>
        Friend ReadOnly Property NotTask() As String
            Get
                Return ResourceManager.GetString("NotTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error adding a new task..
        '''</summary>
        Friend ReadOnly Property NwTskAddedErr() As String
            Get
                Return ResourceManager.GetString("NwTskAddedErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trigger already attached to this task..
        '''</summary>
        Friend ReadOnly Property TrgIsAlrdyAttached() As String
            Get
                Return ResourceManager.GetString("TrgIsAlrdyAttached", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No trigger found for the specified trigger id..
        '''</summary>
        Friend ReadOnly Property TrgNotFound() As String
            Get
                Return ResourceManager.GetString("TrgNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Task with same id is already defined..
        '''</summary>
        Friend ReadOnly Property TskIsAlrdyDefined() As String
            Get
                Return ResourceManager.GetString("TskIsAlrdyDefined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No task found for the specified task id..
        '''</summary>
        Friend ReadOnly Property TskNotFound() As String
            Get
                Return ResourceManager.GetString("TskNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variable is already added to this task..
        '''</summary>
        Friend ReadOnly Property VrIsAddedToTsk() As String
            Get
                Return ResourceManager.GetString("VrIsAddedToTsk", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
