urls = new Array("./pmr_overview_topic.htm",
	"./pmr_record_macro.htm",
	"./pmr_play_back_macro.htm",
	"./pmr_create_executable_macro.htm",
	"./pmr_manage_macros.htm",
	"./pmr_frequently_asked_questions.htm",
	"./pmr_how_to_buy.htm",
	"./pmr_support_and_email_address.htm",
	"./pmr_end_user_license_agreement.htm",
	"./pmr_edit_macros.htm",
	"./pmr_feature_summary.htm",
	"./pmr_system_tray_icon.htm",
	"./pmr_general_options.htm",
	"./pmr_keyboard_shortcuts.htm");