titles = new Array("Overview of Perfect Macro Recorder",
	"Record Macro",
	"Play back macro",
	"Create Executable Macro",
	"Manage Macros",
	"Frequently Asked Questions",
	"How to Buy",
	"Support and email addresses",
	"End-User License Agreement",
	"Edit Macros",
	"Feature Summary",
	"System Tray Icon",
	"General Options",
	"Keyboard Shortcuts");