descriptions = new Array("Overview of Perfect Macro Recorder 1.50 for Windows 98/Me/NT4(SP6)/2000/XP/2003 Top Next Perfect Macro Recorder Perfect Macro Recorder records key...",
	"Record Macro Top Previous Next To start recording click the \"Record\" command button or Right Click Perfect Macro Recorder System Tray Icon and Cho...",
	"Play back macro Top Previous Next To play a recorded macro choose the macro name from the combo box then click Play back button or press the globa...",
	"Executable Macros Top Previous Next With this feature you can convert any macro to an executable file \".exe\" that can be run stand a lone without ...",
	"Manage Macros Top Previous Next When you click My Macros Button the following window will be displayed where you can rename or delete or delete al...",
	"Frequently Asked Questions Top Previous Next Perfect Macro Recorder Frequently Asked Questions What is the macro? What are the system requirements...",
	"How to Buy Top Previous Next You may purchase Perfect Macro Recorder in the following way: 1. CREDIT CARD online now (no processing fee except for...",
	"Support and email addresses Top Previous Next Please contact us at any time about any subject related to our products. We welcome your comments an...",
	"End-User License Agreement Top Previous READ CAREFULLY: This Perfection Tools Software Perfect Macro Recorder v1.50 End-User License Agreement (\"E...",
	"Edit Macros Top Enter topic text here. Copyright © 2008 Perfection Tools Software. All rights reserved. http://www.perfectiontools.com support@per...",
	"Feature Summary Top Copyright © 2008 Perfection Tools Software. All rights reserved. http://www.perfectiontools.com support@perfectiontools.com ",
	"System Tray Icon Top Previous Next If you left click Perfect Macro Recorder icon in the system tray, perfect macro recorder window will be shown. ...",
	"General Options Top Previous Next Play Back Speed: Choose the play back speed [High or normal or low speed]. Record Mouse: If this option is selec...",
	"Keyboard Shortcuts Top Previous Next You can use a shortcut key to perform an action quickly. You can change any shortcut key by highlighting the ...");