#if !defined(AFX__TRAYICONS_H__F1EED804_51C5_4E1F_AEAF_51E1C441ABD5__INCLUDED_)
#define AFX__TRAYICONS_H__F1EED804_51C5_4E1F_AEAF_51E1C441ABD5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_TrayIcons wrapper class

class C_TrayIcons : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_TrayIcons)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xcd7ca542, 0x262e, 0x11da, { 0xa1, 0xc1, 0x0, 0xe0, 0x4c, 0x77, 0xe, 0xeb } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	// method 'GetSysTrayIcons' not emitted because of invalid return type or parameter type
	VARIANT GetIconCount();
	VARIANT Hide(short* index);
	VARIANT FillMSFlexGrid(LPDISPATCH* FlexGrid);
	void sendreview();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__TRAYICONS_H__F1EED804_51C5_4E1F_AEAF_51E1C441ABD5__INCLUDED_)
