// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_trayicons.h"

/////////////////////////////////////////////////////////////////////////////
// C_TrayIcons

IMPLEMENT_DYNCREATE(C_TrayIcons, CWnd)

/////////////////////////////////////////////////////////////////////////////
// C_TrayIcons properties

/////////////////////////////////////////////////////////////////////////////
// C_TrayIcons operations

VARIANT C_TrayIcons::GetIconCount()
{
	VARIANT result;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT C_TrayIcons::Hide(short* index)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_PI2;
	InvokeHelper(0x60030005, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		index);
	return result;
}

VARIANT C_TrayIcons::FillMSFlexGrid(LPDISPATCH* FlexGrid)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_PDISPATCH;
	InvokeHelper(0x60030007, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		FlexGrid);
	return result;
}

void C_TrayIcons::sendreview()
{
	InvokeHelper(0x60030008, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
