pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["actions_gallery.htm","Inside Cacadu &#62; Actions Gallery","Actions Gallery",""],
["advanced_triggers.htm","Triggers &#62; Scheduled Triggers &#62; Advanced Triggers","Advanced Triggers",""],
["cacaduproject_ftsearch.htm","No title","Cacadu Help Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): ",""],
["cacadu_overview.htm","Cacadu &#62; Overview","Overview",""],
["change_cacadu_theme.htm","Inside Cacadu &#62; Change Cacadu Theme","Change Cacadu Theme",""],
["delay.htm","Actions &#62; Delay","Delay",""],
["enable_disable_cacadu.htm","Advanced Features &#62; Enable/Disable Cacadu","Enable/Disable Cacadu",""],
["errors_handler.htm","Actions &#62; Errors Handler","Errors Handler",""],
["errors_pane.htm","Inside Cacadu &#62; Errors Pane","Errors Pane",""],
["error_reporter.htm","Advanced Features &#62; Error Reporter","Error Reporter",""],
["exit_process.htm","Actions &#62; System &#62; Exit Process","Exit Process",""],
["faqs.htm","Cacadu &#62; FAQs","FAQs",""],
["features.htm","Cacadu &#62; Features","Features",""],
["global_constants.htm","Advanced Features &#62; Global Constants","Global Constants",""],
["global_variables.htm","Advanced Features &#62; Global Variables","Global Variables",""],
["groups_ribbon_page.htm","Inside Cacadu &#62; Ribbon Pages &#62; Groups Ribbon Page","Groups Ribbon Page",""],
["help_ribbon_page.htm","Inside Cacadu &#62; Ribbon Pages &#62; Help Ribbon Page","Help Ribbon Page",""],
["history_pane.htm","Inside Cacadu &#62; History Pane","History Pane",""],
["holidays.htm","Triggers &#62; Scheduled Triggers &#62; Holidays","Holidays",""],
["home_ribbon_page.htm","Inside Cacadu &#62; Ribbon Pages &#62; Home Ribbon Page","Home Ribbon Page",""],
["how_to_start_using_cacadu.htm","Cacadu &#62; How to start using Cacadu","How to start using Cacadu",""],
["how_to_start_using_cacadu_in_l.htm","Videos &#62; How to start using Cacadu in less than 2 minutes?","How to start using Cacadu in less than 2 minutes?",""],
["import_and_export_tasks.htm","Advanced Features &#62; Import And Export Tasks","Import And Export Tasks",""],
["main_menu.htm","Inside Cacadu &#62; Main Menu","Main Menu",""],
["main_window.htm","Inside Cacadu &#62; Main Window","Main Window",""],
["message_boxes.htm","Actions &#62; Message Boxes","Message Boxes",""],
["miss_fire.htm","Triggers &#62; Scheduled Triggers &#62; Miss Fire","Miss Fire",""],
["notations.htm","Advanced Features &#62; Notation","Notations",""],
["options.htm","Inside Cacadu &#62; Options","Options",""],
["orderingcacadu.htm","Cacadu &#62; Ordering Cacadu","Ordering Cacadu",""],
["properties.htm","Inside Cacadu &#62; Task Properties","Task Properties",""],
["quick_access.htm","Inside Cacadu &#62; Quick Access","Quick Access",""],
["show_alert.htm","Actions &#62; Message Boxes &#62; Show Alert","Show Alert",""],
["show_message_box.htm","Actions &#62; Message Boxes &#62; Show Message Box","Show Message Box",""],
["shutdown_pc.htm","Actions &#62; System &#62; Shutdown PC","Shutdown PC",""],
["simple_triggers.htm","Triggers &#62; Scheduled Triggers &#62; Simple Triggers","Simple Triggers",""],
["start_application.htm","Actions &#62; System &#62; Start Application","Start Application",""],
["support.htm","Cacadu &#62; Support","Support",""],
["system.htm","Actions &#62; System","System",""],
["system_requirements.htm","Cacadu &#62; System Requirements","System Requirements",""],
["system_tray_icon.htm","Inside Cacadu &#62; System Tray Icon","System Tray Icon",""],
["tasks_list.htm","Inside Cacadu &#62; Tasks List","Tasks List",""],
["tasks_ribbon_page.htm","Inside Cacadu &#62; Ribbon Pages &#62; Tasks Ribbon Page","Tasks Ribbon Page",""],
["tasks_tree.htm","Inside Cacadu &#62; Tasks Tree","Tasks Tree",""],
["task_flow.htm","Inside Cacadu &#62; Task Flow","Task Flow",""],
["tools_ribbon_page.htm","Inside Cacadu &#62; Ribbon Pages &#62; Tools Ribbon Page","Tools Ribbon Page",""],
["triggers_window.htm","Triggers &#62; Triggers Window","Triggers Window",""],
["variables.htm","Advanced Features &#62; Variables","Variables",""]];
