// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_trayicon.h"

/////////////////////////////////////////////////////////////////////////////
// C_TrayIcon

IMPLEMENT_DYNCREATE(C_TrayIcon, CWnd)

/////////////////////////////////////////////////////////////////////////////
// C_TrayIcon properties

/////////////////////////////////////////////////////////////////////////////
// C_TrayIcon operations

BOOL C_TrayIcon::Show(long Icon, LPCTSTR ToolTip)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x6003000e, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Icon, ToolTip);
	return result;
}

BOOL C_TrayIcon::Animate(LPDISPATCH imgList, long Interval)
{
	BOOL result;
	static BYTE parms[] =
		VTS_DISPATCH VTS_I4;
	InvokeHelper(0x6003000f, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		imgList, Interval);
	return result;
}

BOOL C_TrayIcon::StopAnimateing(long NewIcon)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x60030012, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		NewIcon);
	return result;
}

void C_TrayIcon::ShowBalloon(LPCTSTR Prompt, LPCTSTR Title, long IconType, long Timeout)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I4 VTS_I4;
	InvokeHelper(0x60030014, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Prompt, Title, IconType, Timeout);
}

void C_TrayIcon::CloseBalloon()
{
	InvokeHelper(0x60030018, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL C_TrayIcon::Hide()
{
	BOOL result;
	InvokeHelper(0x6003001a, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_TrayIcon::ChangeIcon(long NewIcon)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6003001b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 NewIcon);
}

BOOL C_TrayIcon::GetIsDisplayed()
{
	BOOL result;
	InvokeHelper(0x68030008, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString C_TrayIcon::GetIconToolTip()
{
	CString result;
	InvokeHelper(0x68030007, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_TrayIcon::SetIconToolTip(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030007, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

BOOL C_TrayIcon::GetAnimateState()
{
	BOOL result;
	InvokeHelper(0x68030005, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL C_TrayIcon::GetTrackPopMenu()
{
	BOOL result;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_TrayIcon::SetTrackPopMenu(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

void C_TrayIcon::PopUp(long hmenu, long ParentWindow)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x6003001e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 hmenu, ParentWindow);
}
